### PR TITLE
Micro USB Typ B  - Molex 105017-0001

### PR DESCRIPTION
**Pull request by zh4ng**
Molex Partnr.: 105017-0001
I am not sure about the right filename / partname

@SchrodingersGat

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@zh4ng thanks for the contribution :)

I think you have done a fine job with the filename. 

If you click on the "Details" button under where it says "All checks have failed" you will see where our auto-check scripts have raised some flags. Here are a few key points:

### Documentation
1. Add a datasheet to the doc field
1. Add keywords e.g. usb receptacle surface mount solder tabs to the keywords fiedl

### Set "Surface Mount" attribute
The Placement type should be set to "Surface Mount"

### Line Widths
1. Increase Fabrication layer lines to 0.1m

### RefDes
1. Add a second reference designator to the Fab layer (you can do this by adding text value '%R')

### 3D model
Please rename the 3D model so that it matches the name of the footprint

### Ignore some rules
The auto-scripts are currently a bit buggy and so please ignore for now:
* 10.6
* 6.3
* 6.6

**Comment by zh4ng** [comment]
Ok @SchrodingersGat  , i have lossed the fight against travis ;) How do i fix the KLC 6.4 rule?

**Comment by SchrodingersGat** [comment]
Travis is confused because you have both THT and SMD pads in the part, and it's trying to use rules that don't really work in that case.

Travis checks are currently in the middle of a huge overhaul that should make them a lot better.

Ignore the current errors - looks like you have fixed the ones that really matter. I will have a look at this footprint soon, thanks! :)

**Comment by zh4ng** [comment]
Thx, i am very excited :)

**Comment by SchrodingersGat** [comment]
@zh4ng this is a very high quality footprint, great work!

I only have some minor suggestions:

capture

1. Adjust x-position of RefDes -> 0 (zero)
1. Move "PCB Edge" text inside the footprint boundary
1. Extend the courtyard below the bottom of the footprint
1. Move second RefDes (on F.Fab layer) to position (0,0)
1. Adjust pin-1 markers to make them a bit more compact (suggestion shown)

If you make these adjustments I think we can merge!

**Comment by SchrodingersGat** [comment]
Thanks for the contribution 👍

**Pull request merged**
