### PR TITLE
Move USB_Micro-B_Molex_47346-0001.kicad_mod

### PR DESCRIPTION
**Pull request by evanshultz**
Move from https://github.com/KiCad/Connectors_Molex.pretty as mentioned at https://github.com/KiCad/Connectors_Molex.pretty/issues/39.

Just submitting here without checking and we'll see if Travis turns anything up...

### CODE REVIEW

**Comment by evanshultz** [comment]
Changes made:
- Fixed 3D model path (does the 3D model file need to be moved too?)
- Added ref des text on fab layer

**Comment by evanshultz** [comment]
Datasheet: http://www.molex.com/pdm_docs/sd/473460001_sd.pdf

Image:
image

Further changes:
- Rotated 270 degrees so pin 1 is closest to top left
- Moved everything with respect to the origin so that 0,0 matches the datasheet pin origin
- Corrected origin to put it in the middle of the footprint
- Changed PCB edge marking text to "PCB Edge"
- Changed PCB edge line to F.Fab layer, thinned line to 0.1mm, and shortened it to fit inside the footprint
- Snuggled silk up to the fab lines by half the silk line width
- Flipped positions of ref des and footprint name (ref des is now on top)

Note that the origin of the footprint is not in the geometric center, and it wasn't before, but this is easier to compare with the datasheet. And for this connector, I don't think this KLC violation matters.

Question:
- How to best indicate the PCB edge? It was marked on Dwgs.User but I instead changed to the style https://github.com/KiCad/Connectors_USB.pretty/blob/master/USB_Micro-B_Molex-105017-0001.kicad_mod uses. Does anyone have ideas about what is best?

**Comment by evanshultz** [comment]
@SchrodingersGat @jkriege2 @poeschlr 
Ready for review and, hopefully, merge. If this is good, please also do PR linked above which removes the old version of this connector from the Molex library. Thanks!

**Comment by evanshultz** [comment]
@SchrodingersGat @poeschlr @jkriege2 
Is someone able to review this and the linked case above?

**Comment by SchrodingersGat** [comment]
Hi @evanshultz a couple of suggestions here:

1. Second RefDes on F.Fab could be rotated 90 deg
1. According to the datasheet the origin should be centered on the large pads (see where the footprint measurements are taken from on the recommended layout)


screenshot from 2017-06-26 17-25-31

**Comment by evanshultz** [comment]
@SchrodingersGat Can you please check out the latest commit? It appears I forgot to submit the footprint which matches my image and notes above. My apologies. You can see my image above has been rotated, to conform with KLC pin 1 location, and also has the origin where you suggested (unless I'm mistaken). I believe all issues are addressed.

**Comment by evanshultz** [comment]
@SchrodingersGat Would you be able to take a look? Sorry again for not pushing the latest changes.

**Comment by SchrodingersGat** [comment]
Thanks @evanshultz I think this is good to go :)

**Pull request merged**
