### PR TITLE
USB_Micro-B_Vertical_Molex-105133-0001

### PR DESCRIPTION
**Pull request by zh4ng**
A vertical Mirco USB Connector from Molex

check_kicad_mod.py found:

Violating Rule 10.4

I don't know if this point is here relevant.
Maybe Travis will found more :)

### CODE REVIEW

**Comment by poeschlr** [comment]
The 3D model path should point to a wrl file not to a step file. This is because the stable release does not support step.

**Comment by poeschlr** [comment]
I now had a better look at your ~~model~~ footprint.

For future reference, direct link to the part drawing: http://www.molex.com/pdm_docs/sd/1051330001_sd.pdf
First of all: the pads are on the correct places and have the correct measurements.

Now some bad news:
The description should hold some information about the part. Not only a link to a datasheet.

The drawings on fab layer can be above pads. (you don't need to break up the lines on this layer.)
The size of your rectangle is correct but the position on the y axis is not quite right.
I used the 3d model from molex to determine the following rectangle. For this placed the connector such that the mounting pins are in the center of their pads. (using freecad and kicad stepup)
If i do that the fab rectangle should be from (-4, -1.435) to (4, 1.565)

The courtyard rectangle has some lines that are not straight. (and not on 0.01 grid)
In y direction the courtyard is determined by the mounting pads, in x direction by the component body. It should be from (-4.5, -2.13) to (4.5, 2.13)

I like your pin 1 marker on the silk layer. (good visibility after assembly and still not in the way.)

**Comment by zh4ng** [comment]
It would be a wonder, if the footprint is 100% conform in the first try. Thank you for the "deep look" :) I will fix it tomorrow.

**Comment by zh4ng** [comment]
Ok, i have some trouble with Github :/ the last commit is a little bit out of control.... Uuuua

**Comment by poeschlr** [comment]
Looks like you pushed it in the middle of a merge process.
(that's why the file now looks like a diff message.)

I noticed you used your personal master branch as a source for the pull request. As a tip for the future:
create a separate branch for each pull request.
```
git checkout -b branch_name
git push --set-upstream branch_name
```

I always make sure that the master branch of my personal fork is in sync with the official repo.
For that i add the official repo as upstream (of course you might need to change the remote address to fit your current repo. This is the address for the connectors_usb repo as an example.)
`git remote add upstream https://github.com/KiCad/Connectors_USB.pretty.git`

With that i can simply sync my master branch (If you have the offical repo under another name replace upstream with that name.)
```
git checkout master
git fetch upstream
git pull upstream/master
git push
```
I do this always before i start any work on my repo (And of course after that i do the branching as described above)

**Comment by poeschlr** [comment]
Is there a reason why neither your fab rectangle nor your courtyard rectangle have the same dimensions as i suggested?
(Especially the courtyard seems off. Why -2.2 instead of -2.13)
Did i calculate them incorrectly or did you make a mistake when fixing this footprint?

**Comment by zh4ng** [comment]
Hi Rene,
ok, you are right at the horizontal courtyard line. It is -2.13. My mistake, i do not check the courtyard after i change the fab layer. Now the distance between pad and coutyard is 0.5mm.

With the bottom horizontal courtyard line i have a problem with the KLC Rule 5.3 - 0.01 Grid. The distance between pad and courtyard line is 2.125. Out of my sight the pad and fab layer are edge on edge.

If the pads are all right, my fab layer is buggy.
This is my way to draw the fab layer:

molex_xx

I my case i used 2.8 instead of 2.79. But i think that is not the point. The horizontal fab lines are is still inside the the pads so that the pads are the point to measure the distance to the courtyard.

Maybe I do not see my mistake,therefore we are discussing here.

Other point: Thanks for the git tips :)

PS: Ich hoffe wir reden nicht aneinander vorbei ;)

**Comment by poeschlr** [comment]
I am not on the computer i normally use fer checking pull requests.
But as far as i remember the fab layer was of by only a bit which could be explained by rounding stuff.

The courtyard distance should be 0.5 mm for connectors.
Which means the y coordinate should be: (2.15+1.1)/2+0.5 = 2.125 ~ 2.13 

Here also my freecad sketch that i made to confirm my calculations.
https://www.dropbox.com/s/nzsg7n281kpfito/USB_connector_footprint_problems.fcstd?dl=0

**Comment by zh4ng** [comment]
Ok, we are not far off. I do a commit and you take it apart ... :)

but wait, how do you get the distance of 1.565 mm from the center for the top horizontal fab layer? 

I do this: Center of the upper pad + 0.36mm is the distance for the upper fab layer line. The from there minus 3.0mm to the lower fab layer line.
molex_xy

**Comment by poeschlr** [comment]
Originally i did this in freecad. (Not the drawing i posted. As i said i'm on the wrong pc right now.)
Using your drawing and the information that the mounting pins have a width of 0.3 mm i can calculate everything else. (I got the pin width from the 3d model by molex) 

Remember in kicad y+ is toward the bottom side of the screen.

Do i remember correctly that the two mounting holes are toward the top? (If not everything i calculated for y needs to be multiplied by -1)

Now the calculation: -2.15/2-0.3/2+2.79=1.565
-2.15/2: center of pad
-0.3/2 brings me to the outside of the pin
+2.79 now we are at the "bottom" edge of the part

**Comment by poeschlr** [comment]
> but wait, how do you get the distance of 1.565 mm from the center for the top horizontal fab layer

just to be clear: 1.565 is toward the direction where the single mounting hole is located.
the other one is 1.565-3 = -1.435 (Again assuming the two holes are towards the top of the screen.)

**Comment by zh4ng** [comment]
Ok Rene, you are right. My mistake, upps

Tomorrow i double check the courtyard and fab layer and then i commit....


thanks again.

**Comment by poeschlr** [comment]
Thanks for your contribution.

**Pull request merged**
