### PR TITLE
Added CircularHoles versions of USB Type-C receptacles

### PR DESCRIPTION
**Pull request by Ratfink**
For fab houses that don't support plated slots, it's useful to have footprints with circular holes instead.  This commit adds CircularHoles footprints for Amphenol_12401548E4-2A (from #7, not yet merged) and Amphenol_12401610E4-2A (from #3, merged), otherwise identical to the regular versions.

I don't know if there's a standard suffix for this type of footprint variant, so if there is I'd happily rename these.

Amphenol_12401548E4-2A CircularHoles
Amphenol_12401610E4-2A CircularHoles

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Hi @Ratfink can you please fix the annular ring issues? They need to be at least 0.15mm

**Comment by Ratfink** [comment]
The same comments about annular ring size from #7 apply here, namely that the 0.125 mm annular rings appear to be following the datasheet recommendation.  I wrote "appear to be" because Amphenol didn't explicitly dimension the annular rings in question, but assuming the footprint drawing is meant to be to scale, the annular rings must be 0.125 mm (compare the pad diameter of pin B12 to the alignment hole next to it).

The datasheet is available here (the real download URL seems to be hidden behind some annoying Javascript): https://www.amphenolcanada.com/StockAvailabilityPrice.aspx?From=&PartNum=12401548E4%7e2A

**Comment by SchrodingersGat** [comment]
Does increasing the annular ring invalidate the footprint here? If it doesn't work with `0.15mm` then we'll go with datasheet.

**Comment by SchrodingersGat** [comment]
Thanks for your contributions @Ratfink

**Pull request merged**
