### PR TITLE
Add USB Type-C Plug and Receptacle footprints

### PR DESCRIPTION
**Pull request by Ratfink**
To go along with https://github.com/KiCad/kicad-library/pull/1214, here are footprints for a USB Type-C Plug and Receptacle.

I'm not completely sure where to put the anchor in either footprint.  For the receptacle I put it at the dimension origin in Amphenol's drawing, and for the plug I put it in the middle of the rows of pins.  I realize that it is entirely likely that these are both mistakes.

In general I'm pretty unsure about the plug's footprint.  It's technically a surface-mount part, but it seems unlikely that it would be installed by a pick-and-place machine given that it mounts on the board edge, so maybe it should be Normal instead of Normal+Insert.  Also, I don't know what to do about drawing the connector body since it almost entirely hangs off the board.

### CODE REVIEW

**Comment by poeschlr** [comment]
Would it be possible for you to provide a screenshot of the footprint and a link to the datasheet?
(Makes reviewing of pullrequests a lot easier.)

**Comment by Ratfink** [comment]
Sure thing!
* Amphenol 12401610E4#2A
  * [Information page](https://www.amphenolcanada.com/StockAvailabilityPrice.aspx?From=&PartNum=12401610E4%7e2A) (I can't seem to get a direct link to the PDF drawing, but there's a link on that page on the left)
  * Imgur
* Molex 105444-0001
  * [PDF Drawing](http://www.molex.com/pdm_docs/sd/1054440001_sd.pdf)
  * Imgur

**Comment by SchrodingersGat** [comment]
@poeschlr do you have any issues with these footprints as they stand?

The KLC 9.6 exception is just a rounding error in the check scripts. 

The component origin is harder as there is a mix of SMD and THT pads.

**Comment by Ratfink** [comment]
I feel like it would be right to move the origin of the Amphenol 12401610E4#2A to the center of the part outline.  The pins are all very short (≈ 1 mm) and the connectors are supplied on tape for pick-and-place machines, so treating it like an SMT part would make sense.  It might be a good idea to leave the origin a tiny bit off of the actual center though, since using the actual center would put almost everything off of a 0.01 mm grid.

The Molex 105444-0001 though, I really don't know what the right thing to do about the origin would be.  Making the it in line with the board edge (specifically, the part that extends to the edges of the footprint) might make it easier to use, but would it really be *right*?  Also, maybe the text should be changed to "PCB Edge" to match the Molex-105017-0001 already in this library.

**Comment by poeschlr** [comment]
@SchrodingersGat: As predicted I did not find time to check these footprints until now I will take a look at them later today.

**Comment by poeschlr** [comment]
I just looked at the footprints.
Overall they look ok.

@Ratfink: I agree with everything of your last post. So move the center of 12401610E4 to the center. (you can round it to 0.01mm grid)

For 105444-0001 i would vote for putting the origin on the edge board (but i'm not sure either)
Changing the text might be a good idea as well.

**Comment by Ratfink** [comment]
Okay, I've updated the footprints as discussed.  Here are current screenshots:
Imgur
Imgur

**Comment by poeschlr** [comment]
Sorry for my delay.
I have a question regarding the footprint name.
Do i understand it correctly that for the Molex connector the last 4 digits (everything after "-") define the packaging and surface plating? If there is no other difference i would name the footprint "USB_C_Plug_Molex_105444".

**Comment by Ratfink** [comment]
It does look like that's the case, yes.  I'll rename the part shortly.

Out of curiosity, I also checked the 105017-0001 to see if it should be renamed too.  My conclusion is that it should not, since the 105017-0002 has a different land pattern.

**Comment by poeschlr** [comment]
Thanks for this contribution.

**Pull request merged**
