### PR TITLE
Added Amphenol 12401548E4-2A

### PR DESCRIPTION
**Pull request by Ratfink**
The hybrid version of Amphenol 12401610E4-2A.

screenshot from 2017-08-05 12-52-59

Datasheet (link on this page, can't seem to get a direct link):
https://www.amphenolcanada.com/StockAvailabilityPrice.aspx?From=&PartNum=12401548E4%7e2A

The annular rings of the B pins in the footprint are only 0.125 mm, which is smaller than KLC allows.  I believe this matches Amphenol's drawing (though it doesn't appear they explicitly dimensioned the annular rings, the PCB layout drawing is to scale, and the annular rings certainly look like 0.125 mm).

### CODE REVIEW

**Comment by Shackmeister** [comment]
@SchrodingersGat @evanshultz @jkriege2 @poeschlr 
doesnt datasheet always overrule KLC?

**Comment by SchrodingersGat** [comment]
Does increasing the annular ring invalidate the footprint here? If it doesn't work with `0.15mm` then we'll go with datasheet.

**Comment by Ratfink** [comment]
It wouldn't invalidate the footprint *per se*, but it would make the pad-pad clearance a mere 0.1 mm.  I see nothing about pad-pad clearance in the KLC, so I suppose that isn't a major problem, but it does violate a lot of fab houses' design rules.  As a result, I personally wouldn't have much use for the footprint if I did have to make that change, but I'll still change it if that's what you feel is right.

**Comment by SchrodingersGat** [comment]
Yeah that's only 4mils. Ok, in this case we should ignore the annular ring rule.

**Comment by Ratfink** [comment]
If the annular rings are okay, is there anything left that's preventing this from being merged?

**Comment by SchrodingersGat** [comment]
Nope! Thanks for your contributions :)

**Pull request merged**
